apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-escolar-pvc
  namespace: api-escolar
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard 