apiVersion: v1
kind: PersistentVolumeClaim # PersistentVolumeClaim é um recurso que cria um volume persistente para o seu aplicativo
metadata:
  name: api-escolar-pvc
  namespace: gestao-escolar
spec:
  accessModes:
    - ReadWriteOnce # ReadWriteOnce significa que o volume pode ser lido e escrito por um único node
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath